### ISSUE TITLE
BartyCrouch does not really find files recursively

### ISSUE THREAD

**Issue by tomaskraina** [Flinesoft/BartyCrouch#100]
I noticed that `NSLocalizedString`s in files that are in double nested folders or higher are not found by bartycrouch.

`bartycrouch code -p "../MyProject" -l "../MyProject" --default-to-keys -v`

Example:
- MyProject/File.swift - found
- MyProject/Model/File.swift - found
- MyProject/Model/NestedFolder/File.swift - **not found**

**Comment by tomaskraina** [comment]
If you could point me how to start running the project locally from source and where to look to fix it, I would prepare a pull request.

Thanks!

**Comment by Dschee** [comment]
@tomaskraina thanks for reporting this. Best way to fix this is to add tests with such a nested folder structure under `Tests/Assets` where `NSLocalizedString` entries from the nested file isn't found so the tests are first failing (probably in `StringsFilesSearchTests`). Then you can fix the code in `StringsFilesSearch` until the test is passing and send the result (including the tests) as a pull request.

If you want to run BartyCrouch locally against your project, you need to pass arguments on launch with the BartyCrouch CLI scheme like in the following image:

![bildschirmfoto 2018-06-28 um 13 35 45](https://user-images.githubusercontent.com/6942160/42031937-4142da64-7ad8-11e8-8026-50f8fca9867c.png)

I hope this helps.

**Comment by tomaskraina** [comment]
Hi @Dschee, after I added the tests for this case, I found out that it was actually Xcode messing up with my files so that BartyCrouch couldn't find them.

Anyway, as the tests for finding swift files weren't presented in the project, I have added them in this PR - https://github.com/Flinesoft/BartyCrouch/pull/101
