### ISSUE TITLE
interfaces Updates .strings files of Storyboards 

### ISSUE THREAD

**Issue by iKushalManiyar** [Flinesoft/BartyCrouch#119]
Hello, 

I have one UILable on my storyboard and I've named them "Test". I want this string in Localizable.strings. Is it possible? 

Thanks in advance

**Comment by Dschee** [comment]
Storyboards have their own .strings files, they are not meant to be localized in the Localizable.strings file. That is only there for localization Strings in code. See the Apple Documentation [here](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/InternationalizingYourUserInterface/InternationalizingYourUserInterface.html#//apple_ref/doc/uid/10000171i-CH3-SW3) for more information.

Does this help you? Maybe I misunderstood your question.

**Comment by Dschee** [comment]
Closing this since it's more a question that should be asked on StackOverflow or the problem needs to be further clarified.
