### ISSUE TITLE
Whitespaces in project name/path don't work

### ISSUE THREAD

**Issue by Dschee** [Flinesoft/BartyCrouch#12]
Projects with whitespace in name or path don't seem to be recognized.

**Comment by Dschee** [comment]
Seems like there's more to this problem than handled with #17. See #21 for more information.

**Comment by ashleymills** [comment]
I was also suffering from the `tmpstrings not found` issue. 

Path to my project folder was  `/Projects/Xcode Projects/Flipper/Project Name/`

Moving to `~/Desktop/Flipper/Project_Name` fixed the problem

**Comment by Dschee** [comment]
Many changes to the project were made since last activity in this issue and I personally never had problems with whitespaces in folder paths, so I consider this fixed unless somebody tells me otherwise. If problems appear, an example project would be very helpful.
