### ISSUE TITLE
Version not updated!?

### ISSUE THREAD

**Issue by jjorn** [Flinesoft/BartyCrouch#129]
The command `--version` returns 4.0.0, although the latest version (4.0.1) has been installed.

**Comment by Dschee** [comment]
That's right, it was forgotten in the latest release. The appropriate line is [here](https://github.com/Flinesoft/BartyCrouch/blob/stable/Sources/BartyCrouch/main.swift#L10).

**Comment by Dschee** [comment]
I'm closing this since it's not possible to fix it without a new release and when doing a new release, we have to bump the version anyways (and hopefully won't forget it again! 😄 ).
