### ISSUE TITLE
Issiues after updating BartyCrouch

### ISSUE THREAD

**Issue by UtkuDalmaz** [Flinesoft/BartyCrouch#130]
Hi,

<img width="280" alt="Screen Shot 2019-04-05 at 16 32 07" src="https://user-images.githubusercontent.com/2130592/55631304-6c128080-57c0-11e9-9a77-5869909d115f.png">

I am having some issues after updating BartyCrouch.

Errors in the screenshot are related to 
`let occupation = NSLocalizedString(String(describing: dictJSON["occupation"]!), comment: "")`
I am using NSLocalizedString directly for string that returns from service. 
How to make it right?

Other issue
`/Users/username/Developer/App:-1: BartyCrouch:  Could not find 'SupportedLanguage' enum within 'BartyCrouch' enum within path.`

Warnings
How to silence empty value warnings?

Question
There was an option provided in the earlier versions such as -a to keep manually entered localizations. How can I use/disable it in the new version?

**Comment by Dschee** [comment]
Please create separate issues for each question or problem you have. That way the title of the issue will also be more useful for others having the same issue. I will answer your questions in there.

Please also note that we have an official [Migration Guide](https://github.com/Flinesoft/BartyCrouch/blob/stable/MIGRATION_GUIDES.md#upgrade-from-3x-to-4x) for upgrading from 3.x to 4.x. Make sure to read it before opening any issues.

I'm closing this one.
