### ISSUE TITLE
Need Clarification

### ISSUE THREAD

**Issue by Sunitadaffodil** [Flinesoft/BartyCrouch#137]
I am new to iOS development and requirement in one of my project is Localization. So I came across BartyCrouch (as suggested all over stackoverflow)

I Tried downloading  and running "Demo" project. I have successfully compiled the project and tried playing around it. So here, I need clarification on some points below.

1- Expected BartyCrouch to add strings to Localizable.string file (which is happening)
2- Expected to automatically update Localizable.string  for newly added string in code (which is happening)
3- Expected to configure BartyCrouch (happening)

Issues/places where I got stuck are below
1- Ran bartycrouch init ,but could not found .bartycrouch.toml file
2- I was expecting BartyCrouch would add translations also for newly added string for different languages. But it's not happening. May be I am doing something wrong. So need confirmation on this part.

I really appreciate , if you can clarify these things to me. I know you guys are very busy , but really appreciate if someone take out some time to improve my understanding (Not urgent but whenever you guys have time).

**Comment by Dschee** [comment]
Hello @Sunitadaffodil, great that you're interested in BartyCrouch as part of your iOS learning path and welcome to the community!

Please note that in order for us to be able to help, we need as much information as possible, in the best case you would provide us an example project – but if not possible, you could also send screenshots that clarify the project structure (file-wise). Also, the exact steps you took, including the commands you executed would be helpful.

Thus, regarding question 2, I can not help without further information. But question 1 could be simply, that all files starting with a `.` at the beginning like `.bartycrouch.toml` are **hidden files** in macOS. To toggle your hidden files from off to on (and vice versa), you can simply open your project in Finder and hit `Cmd`+`Shift`+`.` on your keyboard.

I hope this helps a little.

**Comment by Dschee** [comment]
Closing this as this is more an open question and not a fixable issue. Feel free to ask further questions if you have any.

**Comment by Sunitadaffodil** [comment]
Thanks a lot for the reply.

I am able to to see .bartycrouch.toml file (which was hidden).

Please find link of the demo app
https://drive.google.com/drive/folders/14ICpMOxcJD1vC0zzMEsIz9oqG3Y2WZuN?usp=sharing

Rephrasing my question: 
I was expecting Bartycrouch would add translations for newly added strings for different languages.

but now, Bartycrouch add a particular key in .string file and not adding translations.

**Comment by Dschee** [comment]
@Sunitadaffodil Glad I could help a little. I downloaded your Demo app from your link, but there's no `.bartycrouch.toml` file in there, nor is there a build script. It just looks like the Demo example from the BartyCrouch repo. I don't understand what you're doing within the Demo repo?

By default, BartyCrouch will add keys for each language supported for new Strings in Code. By default, BartyCrouch doesn't add translations. You would need to configure the `translate` option on the [update command](https://github.com/Flinesoft/BartyCrouch#update-subcommand) to do so, which will use Microsoft Translator for automatic translations.

Or maybe I misunderstood your question?

**Comment by thesunita** [comment]
@Dschee Thanks for reply. I had uploaded wrong Demo project. Sorry to bother you for that.

Ok, I got it now, I was just wanted to know, whether  BartyCrouch would add translations automatically. So if I want to add translations automatically , then I need to configure the translate options on the update command ?

**Comment by thesunita** [comment]
Thanks

**Comment by Dschee** [comment]
Yeah exactly. You're welcome.
