### ISSUE TITLE
Code transform task is very slow

### ISSUE THREAD

**Issue by Kondamon** [Flinesoft/BartyCrouch#146]
The code transform task is very slow (appr. 22 seconds) for me with BartyCrouch 4.0.2

configuration file:
        [update]
        tasks = ["interfaces", "transform", "normalize"]

        [update.interfaces]
        path = "."
        defaultToBase = false
        ignoreEmptyStrings = false
        unstripped = false

        [update.code]
        codePath = "."
        localizablePath = "."
        defaultToKeys = false
        additive = true
        unstripped = false

        [update.transform]
        codePath = "iOS-App/."
        localizablePath = "."
        transformer = "swiftgenStructured"
        supportedLanguageEnumPath = "."
        typeName = "BartyCrouch"
        translateMethodName = "translate"

        [update.normalize]
        path = "."
        sourceLocale = "en"
        harmonizeWithSource = true
        sortByKeys = true

        [lint]
        path = "."
        duplicateKeys = true
        emptyValues = true

- Xcode Version 10.3 (10G8)
- macOS Version 10.14.5 (18F132)
- BartyCrouch versions 4.0.2 
- Project with appr. 150 files and up to appr. 300 lines of code per file. Approximately 150 localized strings.

**Comment by Dschee** [comment]
Thank you for reporting this. Did you already try providing more specific paths for all options including `path` as suggested in the README? For example for `localizablePath` and `supportedLanguageEnumPath` within the `update.transform` config. Also please note that you don't need to write `iOS-App/.`, you can simply use `iOS-App` for the path.

**Comment by Kondamon** [comment]
Thank you for your quick reply. I added this line and the execution time decreased from 22 seconds to 0.8 seconds, thanks!


    supportedLanguageEnumPath = "iOS-App/Supporting Files"

**Comment by Dschee** [comment]
Glad I could help. 😃
