### ISSUE TITLE
BartyCrouch.translate is replaced/transformed only by case-insensitive code

### ISSUE THREAD

**Issue by Kondamon** [Flinesoft/BartyCrouch#147]
I'm using that configuration: https://github.com/Flinesoft/BartyCrouch/issues/146

Entering this string in a Swift file:

    BartyCrouch.translate(key: "Formatters.UserGoalFormatter.setYourGoalDuration", translations: [.en : "Set your goal duration"])

Results to case-insensitive (giving compiling error):

    L10n.Formatters.Usergoalformatter.setyourgoalduration

But correct would be:

    L10n.Formatters.UserGoalFormatter.setYourGoalDuration

It seems like BartyCrouch is just transforming to case insensitive texts but this doesn't work together with SwiftGen.

**Comment by deden** [comment]
How about use this format, @Kondamon ? :
```
BartyCrouch.translate(key: "Formatters.user_goal_formatter.set_your_goal_duration", translations: [.en : "Set your goal duration"]) 
```

**Comment by Kondamon** [comment]
Ok, I didn't know this. However, this has drawbacks in searching strings in the dict files and in code. Because when searching for "Formatters.UserGoalFormatter" in XCode finds all occurences in the code via L10n... AND all translation keys in the different dict files at the same time. Then it's possible to switch between all results via a simple click. And beyond this it's very uncommon in Swift to use '_'. 

What files in BartyCrouch needs to be changed to just keep the upper case letters and not to replace these by small letters by default?

**Comment by Dschee** [comment]
Here's a pointer to where on a cursory look you probably need to make the change:
https://github.com/Flinesoft/BartyCrouch/blob/stable/Sources/BartyCrouchKit/FileHandling/TranslateTransformer.swift#L107

I hope this helps. Please note that in the best case unit tests should be written first with a failing test for this (using something like your example above) and then the code should be changed to make the tests pass at least.

**Comment by resterampeberlin** [comment]
> Ok, I didn't know this. However, this has drawbacks in searching strings in the dict files and in code. Because when searching for "Formatters.UserGoalFormatter" in XCode finds all occurences in the code via L10n... AND all translation keys in the different dict files at the same time. Then it's possible to switch between all results via a simple click. And beyond this it's very uncommon in Swift to use '_'.
> 
> What files in BartyCrouch needs to be changed to just keep the upper case letters and not to replace these by small letters by default?

I strongly support that since it will ease the workflow and readabilty

**Comment by Jeehut** [comment]
@Kondamon What's the state of this? Do you still plan to implement this?
Please note that translations keys are not Swift code and thus don't need to follow Swift conventions. They can have their own conventions and when it comes to cross-platform keys that are identical, the `formatters.user_goal_formatter` is actually the one which works best. SwiftGen takes care of the conversion to the Swift conventions for us.

The use case you mention with the search that shows both, the code and the localization sounds like an edge case to me. But having all that said, I'm totally not against adding support for your use case, please just make sure to add tests and send a PR, then I'll happily merge.

**Comment by Kondamon** [comment]
@Jeehut, I haven't had time to start with this yet. It's still an issue for us and we are interested in having this issue solved. However, unfortunately I can not spend time on the issue at the moment and.
