### ISSUE TITLE
Avoid localization from Pods

### ISSUE THREAD

**Issue by nonpensavo** [Flinesoft/BartyCrouch#152]
Everytime I run update on bartycrouch, my Localizable.string files are messed up with every NSLocalizedString used inside Pods, which I dont want. Its just too much. 
I tried to search in older issues or find the way, but there is no clear answer and nothing what I tried worked. 
Most annoying part is that these unneeded strings are in random mess order with my project strings so cleaning is tough every time. 

For example, its picking up NSLocalizedString from Pods/Pods/AWSCore/AWSMTLManagedObjectAdapter.m, along with many other files in several Pods. 
Id be ok to add Pods completely to ignore list, any way how to do it?

**Comment by Jeehut** [comment]
@nonpensavo Thank you for reporting this. Actually we already fixed this issue by excluding any Pods directory by default. Additionally, you can try fixing this by specifying something different than `.` for the different `path` options in the `.bartycrouch.toml` file as suggested in the README.

Could you also please post your `.bartycrouch.toml` file contents and BartyCrouch version?

**Comment by nonpensavo** [comment]
Thank you, I am not sure about `.` but will try using documentations.
I also read before from closed issues that it have been solved in one of the PR by adding `Pods` to ignore list but still as a new user to this solution its taking some time to me to understand why it wouldnt work as is.
Version 4.0.0, first time installed as 4.0.0, project init and update all using same version. 

`[update]
tasks = ["interfaces", "code", "transform", "normalize"]

[update.interfaces]
path = "."
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false

[update.code]
codePath = "."
localizablePath = "."
defaultToKeys = false
additive = true
unstripped = false

[update.transform]
codePath = "."
localizablePath = "."
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
path = "."
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "."
duplicateKeys = true
emptyValues = true
`

**Comment by Jeehut** [comment]
Sure, no worries. As you can see, all the keys that contain `path` in your configuration are just set to `.` which means "the root folder". Just set all of them to the most exact folder you can come up with, this is recommended as this will both make any commands run faster and also fix the Pods directory bug you seem to come across. For example, all `path` can usually be set to something like `Sources`/`App`/`YourProjectName` folder, `localizablePath` can sometimes set to a subfolder like `App/Resources` and `supportedLanguageEnumPath` (if you configured it) can be set to something like `App/SupportingFiles` depending on where you placed those files.

I hope this helps.

**Comment by nonpensavo** [comment]
> Sure, no worries. As you can see, all the keys that contain `path` in your configuration are just set to `.` which means "the root folder". Just set all of them to the most exact folder you can come up with, this is recommended as this will both make any commands run faster and also fix the Pods directory bug you seem to come across.
> 
> For example, all `path` and `codePath` can usually be set to something like `Sources`/`App`/`YourProjectName` folder, `localizablePath` can sometimes set to a subfolder like `App/Resources` and `supportedLanguageEnumPath` (if you configured it) can be set to something like `App/SupportingFiles` depending on where you placed those files.
> I hope this helps.

It worked well, I also removed "code" from tasks for better performance (Swift only) and updated transform section of configuration file to following as you adviced
```[update.transform]
codePath = "App"
localizablePath = "App/Supporting Files"
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"```

Pod localizations didnt appear again! Thank you.

**Comment by Jeehut** [comment]
Sure, you're welcome! Glad I could help. :)
