### ISSUE TITLE
Use multiple `codePath` locations

### ISSUE THREAD

**Issue by patricks** [Flinesoft/BartyCrouch#155]
Is there any way to set multiple codePath locations? My project structure looks like this:

-/Project
----------/FrameworkA
----------/FrameworkB
----------/App
----------/Pod

I want bartycrouch to update the localization file in `APP` and include the folders `FrameworkA` and `FrameworkB`, but the `Pod` should be ignored. Is this possible? It didn't find a working solution.

**Comment by Jeehut** [comment]
@patricks Thank you for reporting this. Yes, this is a problem of the current configuration options and while easy to fix, I just couldn't find the time recently to add this. This could be added to the project as a non-breaking change by changing all `path` variables `paths` and accepting an array of Strings for each. Also, for this not to be a breaking change, we could simply also continue to allow singular `path` variables and just convert them to a single-value array.

The only problem is, I really don't have the time at the moment to implement this myself. So either @fredpi or someone else would hneed to implement this and post a PR. I will take my time to review it to make sure this feature is added quickly, promise. Just ping me if I don't, to remind me – this is quite an important and easy-to-add feature, I think.
