### ISSUE TITLE
Add support to run subtasks seperately

### ISSUE THREAD

**Issue by ndreisg** [Flinesoft/BartyCrouch#166]
I am trying to reduce the build time of my app, so I came up with the idea to split up the BartyCrouch build phase into 3 separate build phases:

- one build phase to run `update.code` with my .swift files as input files, so it will only run when I made changes in my code.
- one build phase to run `update.interfaces` with my .storyboard files as input files, so it will only run when I made changes in the UI.
- and finally a build phase to run `lint` and `update.normalize` with the .strings files as input files.

Unfortunately this currently doesn't seem to work since the command line tool does not offer any option to run a separate update subtask. Am I missing something?

I think one of these two enhancements would be a very good addition:
- add a 'subtask' parameter to the update command, eg. `bartychrouch update code`
or
- add a parameter to specify a different configuration file path, so you could configure your subtasks in separate configuration files

**Comment by Jeehut** [comment]
@ndreisg Thank you very much for this suggestion. Sounds reasonable and I think adding an option to specify a path for the configuration file is the way to go here to keep things simple in the code base but still allowing calling bartycrouch in a flexible way.

Please note that I'm currently working on another project in my free time so won't have much time to invest here. But before I start my next iOS project, I plan to make a new major BartyCrouch release, where I would like to improve on several aspects, I think it makes sense to solve this then as well. But that will still take some time, probably in the summer this year. If you need this feature earlier, feel free to post a PR – I'd happily review it and make a minor release! :)

**Comment by Jeehut** [comment]
I think the most generic and easiest solution to fix your problem would be if we add an option to BartyCrouch to specify a path for the BartyCrouch config file. Then, you could create multiple config files, where in each only the steps you want to run are turned on. Then you can run them whenever you need to.

**Comment by ndreisg** [comment]
Yes that would indeed solve my problem. 
I'm sorry I didn't have time yet to look into it, maybe I will find some time on the weekend to make a PR :)

**Comment by Jeehut** [comment]
Sounds good! Looking forward to it. 👍

**Comment by Jeehut** [comment]
@ndreisg I've decided to implement this myself as it's not a big feature.
The fix for this was just released in [4.2.0](https://github.com/Flinesoft/BartyCrouch/releases/tag/4.2.0) and should be available via Homebrew [soon](https://github.com/Homebrew/homebrew-core/pull/53644). 🎉

**Comment by ndreisg** [comment]
Thank you very much for adding this, I will test it soon. Sorry I didn't find the time to make a PR :/
