### ISSUE TITLE
Not working transform in swift5.2 and Xcode11

### ISSUE THREAD

**Issue by noppefoxwolf** [Flinesoft/BartyCrouch#170]

**Comment by noppefoxwolf** [comment]
I fixed this.
https://github.com/Flinesoft/BartyCrouch/pull/171

**Comment by alphatroya** [comment]
Yes, I confirm that. BartyCrouch `transform` command is broken after I've updated XCode version to 11.4

**Comment by Jeehut** [comment]
Fixed via #172. Released 4.1.0 (homebrew-core update [pending](https://github.com/Homebrew/homebrew-core/pull/52825)).
