### ISSUE TITLE
Warning in Strings.swift generated by SwiftGen: "BartyCrouch:  Could not parse syntax tree of Swift file."

### ISSUE THREAD

**Issue by jopvanheesch** [Flinesoft/BartyCrouch#174]
I have used BartyCrouch before, but it no longer seems to work. Probably I am doing something wrong, but I cannot find what. Attached is a simple project in which "BartyCrouch.translate(key: "Welcome",  translations: [.english: "Welcome!"])" is not being transformed:

[OneMoreTime.zip](https://github.com/Flinesoft/BartyCrouch/files/4469613/OneMoreTime.zip)

**Comment by Jeehut** [comment]
@jopvanheesch What version of BartyCrouch do you have installed? `bartycrouch version`

This sounds similar to https://github.com/Flinesoft/BartyCrouch/issues/170 which we fixed in the latest version `4.1.0`. Can you please make sure you have the latest version?

**Comment by jopvanheesch** [comment]
Thanks for the quick response! Indeed, I had version 4.0.0. I had used the brew update command instead of brew upgrade. Keep up the good work!
