### ISSUE TITLE
Publish 4.1.0 to CocoaPods

### ISSUE THREAD

**Issue by djbe** [Flinesoft/BartyCrouch#175]
Similar to the last release, some things are missing for cocoapods release:
- `portable_bartycrouch.zip` asset is missing from the release (on GitHub)
- Pretty sure the podspec changes must be part of the tagged release.
- Push the release to Cocoapods using `pod trunk push`

**Comment by Jeehut** [comment]
@djbe Thanks for the pointer. Fixing now! 🎉
