### ISSUE TITLE
Working with multiple targets

### ISSUE THREAD

**Issue by hactar** [Flinesoft/BartyCrouch#177]
We have an app which as multiple targets: The app, the iMessage target and the Apple watch target. Each is in its own subfolder, and each has its own localizable.strings file. If I run bartycrouch on our project, it adds all strings to all localizable.strings file, independent of target. So the iMessage localizable.strings file now contains all strings from the app target too, and vice versa.

How do I set up bartycrouch so it does not do that, or so that runs once per target folder, so that the strings are not mingled?

Thanks for any insights...

**Comment by Jeehut** [comment]
@hactar I think this is related to #166, please see [this comment of mine](https://github.com/Flinesoft/BartyCrouch/issues/166#issuecomment-614462837) where I basically suggest that we make the `.bartycrouch.toml` configuration file path configurable, at the moment it's always assumed to be at the current location. But if you were able to specify it's location, you could simply create one `.bartycrouch.toml` file for each of your targets (within their directories) and run `bartycrouch` 3 times, each time specifying a different config file path. That should solve your problem as well.

Note that @ndreisig said he will try to implement this on this weekend, so either wait for him to implement it or do it yourself (and best mention him so he knows). I think it's a good starter contribution task. :)

**Comment by hactar** [comment]
Thanks @Jeehut , had the same idea and tried it over night, works well. I now simply have 1 config file per target folder. As the config files are better when they are slightly different (watch doesnt need code step, watch extension doesnt need interface step) I'd say this is the ideal solution. Will close as I consider it solved :). If this is the suggested solution feel free to comment and I'll contribute some documentation.

**Comment by Jeehut** [comment]
This was fixed via #181 and released in [4.2.0](https://github.com/Flinesoft/BartyCrouch/releases/tag/4.2.0) and should be available via Homebrew [soon](https://github.com/Homebrew/homebrew-core/pull/53644). 🎉
