### ISSUE TITLE
Generated strings file starts with empty line

### ISSUE THREAD

**Issue by hactar** [Flinesoft/BartyCrouch#178]
The strings files generated by bartycrouch start with an empty line, for example

```

/* No comment provided by engineer. */
" away" = " away";
```

We use lingohub for translation, which returns the translated files without the empty line. This in turn means that upon rerunning bartycrouch, the new line is readded, causing our git commits to look terrible.

Is there any way to get bartycrouch to not add that new line at the top? `unstripped` true or false, in both the code and interface section, appear not to have an effect.

Thanks.

**Comment by Jeehut** [comment]
@hactar Thank you for reporting this issue. Actually, `unstripped` is exactly introduced for this purpose that when integrating to specifically LingoHub it works as expected. So I consider it a bug that turning on `unstripped` doesn't keep the newlines at beginning and end.

Having this said, I guess having a newline at the beginning of the file doesn't make any sense anyways, so even the default behavior should be changed. Will see if I can take a look at this during this week. If you want, you can of course take a stab yourself and post a PR with the change. It's probably easy to fix and therefore a good starter bug.

**Comment by hactar** [comment]
Fixed by PR #180.

**Comment by Jeehut** [comment]
This was fixed via #180 and released in [4.2.0](https://github.com/Flinesoft/BartyCrouch/releases/tag/4.2.0) and should be available via Homebrew [soon](https://github.com/Homebrew/homebrew-core/pull/53644). 🎉
