### ISSUE TITLE
Remove Unused Strings Option

### ISSUE THREAD

**Issue by thejeff77** [Flinesoft/BartyCrouch#185]
## Problem Statement
If a key for a localization "some_unused_string" is no longer used in the codebase, I'd like it to be removed from all .strings files automatically

## Suggested Solution
Add a custom command to remove unused string keys.

## Example Usage
bartycrouch update -x -r

Will remove unused strings.

## Possible Involvement

 - I could help with testing: I'll test the crap out of this for anyone who wants to take it on.

**Comment by Jeehut** [comment]
@thejeff77 Thank you for reporting this idea. I would like to ask you if you want to have a command line option for one-off cleanups or if you would prefer to have a continuous cleanup on each build (via build script). In the latter case I would prefer if the option became part of the configuration file, something like `cleanupUnusedKeys`.

Also note that for this we will probably also need something like a `usageSearchPaths` to provide the paths that should be searched for usage. But I think as an option this would make sense. 👍

**Comment by thejeff77** [comment]
I could see not wanting to commit it right away in case the usage search paths isn't configured correctly. My guess is that there are some people who'd try this out without proper use of source control. Would be nice to have the ability to get warned about it before committing changes that delete values. 

A continual cleanup would be great though once its configured correctly by the user. I love the configuration option. Thoughts on an `unusedKeysWarning` type of config to add to the linter? Warning could be something like "key is unused, use cleanupUnusedKeys to enable auto-cleanup".

Dunno... honestly I'll take what I can get - just throwing out a couple thoughts on it. I'll definitely have source control all setup to be able to revert any undesired changes for the n=1 study of just me. You could always add the one cleanup key and if you get complaints then iterate on it with adding in a linter option or something.

Third idea... add something to the linter option, then if the user deletes the string from the configured base localization file then bartycrouch would automatically remove the key from the rest of the *.strings files and sync them all up (after verifying it is unused). I.E. `autoSyncDeletesOfUnusedKeysFromBase` or something...

**Comment by Jeehut** [comment]
Thank you for that write-up and the brainstorming. After thinking about this again, I think as a first step we should only work on a `unusedKeys` option for the linter. I think getting pointed to any keys that are not used anywhere and letting people clean those up manually is the safest option here, so we should probably start with that.

That will also allow us to improve the code that finds those unused keys over time and with feedback from people. Once we feel that there are basically no false positives, we can introduce an autocorrection within the `update` command using the same code.

Having that said, I think even the initial implementation should detect different kinds of references:
- `NSLocalizedString("key", comment: nil)`
- `L10n.key` ([SwiftGen](https://github.com/SwiftGen/SwiftGen))
- `R.string.localizable.welcome()` ([R.swift](R.string.localizable.welcome))
- `"key".localized()`, `"key".localized"`, `"key".localize`, `"key".l10n()` (see [Localize-Swift](https://github.com/marmelroy/Localize-Swift), [Localize](https://github.com/andresilvagomez/Localize), [L10n-swift](https://github.com/Decybel07/L10n-swift))

Note that for SwiftGen and R.swift we also need to add support for variable based usage like this:

```swift
let typeL10n = L10n.self
// ...
label.text = typeL10n.key
```

**Comment by thejeff77** [comment]
Gotcha, I haven't looked at SwiftGen or R.swift, but it sounds like you know where to go next.

The one thing I'd give another thought on is the manual cleanup. I wouldn't mind cleaning up unused keys from the configured master strings files from warnings, but to me it would be necessary to be able to sync the deletes to the other *.strings files. The thought of doing manual cleanup of unused keys in 23 language files makes me want to throw my head through a plate glass window. Overly dramatic but it would be a long process to manually cleanup all strings files. I'm not sure how it currently works today. If I cleaned up an unused key in 22 of the 23 files and missed one, then built the project with the "update" command, would it sync the string back to the 22 I had deleted the string from?

**Comment by Jeehut** [comment]
If you use the `normalize` update subcommand and have `harmonizeWithSource` set to `true` (which is the case by default), then you‘d only need to delete the key from the source locae, the others will be deleted automatically on the next `update` execution. I hope that helps to save the poor head and also the poor glass. 😊

**Comment by thejeff77** [comment]
I think with this added context, all the heads and all the glass will be very safe with this new linting option :)

**Comment by FlineDevPublic** [comment]
Revisiting this again after some time, I think this feature is out of scope of this tool. A combination of other tools (SwiftGen + Periphery) can do exactly what you're asking for. See also my comment [here](https://github.com/Flinesoft/BartyCrouch/issues/233#issuecomment-1013225990). Closing.
