### ISSUE TITLE
"Unused" strings are removed from Localizable.strings

### ISSUE THREAD

**Issue by faithfracture** [Flinesoft/BartyCrouch#187]
I'm pretty sure this is probably expected behavior & not a bug - I'm probably just plain doing something stupid & need correction, but here's the scenario:

I receive some metadata from a remote server. I use that metadata to determine which strings to use when populating a specific table view with rows, and I need those strings to be translated. The metadata is not user-friendly on it's own, and contains other information I also need to store to map between the string the user sees and a couple different things on the server. Unfortunately, our server doesn't have the capability to send localized content. For this reason, I have all of the potential metadata saved in several Plists, which look similar to:

```
<key>SOME_SERVER_ENUM_VALUE</key>
<dict>
    <key>eventType</key>
    <string>otherMetadataServerHasMappedToOtherThings</string>
    <key>localizeableStringKeyOnMobileClient</key>
    <string>MyKeyToAStringIn.Localizable.strings</string>
</dict>
```

For a given key `MyKeyToAStringIn.Localizable.strings` I will have a matching entry in `Localizable.strings`:

```
"MyKeyToAStringIn.Localizable.strings" = "Friendly User Facing String That Needs Localized";
```

I've gone through and added all the key / value pairs in my `Localizable.strings` file. When I run `bartycrouch update`, all of those strings get removed.

Here's my `.bartycrouch.toml` contents:

<details><summary>.bartycrouch.toml</summary>
[update]
tasks = ["interfaces", "code", "transform", "normalize"]

[update.interfaces]
path = "./src"
defaultToBase = true
ignoreEmptyStrings = false
unstripped = false

[update.code]
codePath = "./src"
localizablePath = "."
defaultToKeys = false
additive = false
unstripped = true

[update.transform]
codePath = "./src"
localizablePath = "."
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.normalize]
path = "./src"
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "."
duplicateKeys = true
emptyValues = true
</details>

Do I have something configured incorrectly? Is there some way I can prevent this from happening, or is this just expected behavior? If it is expected, can you suggest a workaround? My initial thought was to have a separate `.strings` file marked for localization & have Bartycrouch not interact with it, but I wanted to ask here if there was an alternative to that.

## Specifications

  - Version: BartyCrouch 4.0.2
  - Platform: iOS
  - IDE Version: Xcode 11.4.1

**Comment by Jeehut** [comment]
@faithfracture Yes, this is just a configuration issue. In you `.bartycrouch.toml` I can see that `additive` is set to `false`. As described in the README under `code` options, the `additive` option does this: "Prevents cleaning up keys not found in code."

So just set it to `true` (which is the case by default by the way) and it should work as expected.

**Comment by faithfracture** [comment]
Yep, that took care of it. Thanks!
