### ISSUE TITLE
Normalize: harmonizeWithSource=false parameter is simply ignored

### ISSUE THREAD

**Issue by lechuckcaptain** [Flinesoft/BartyCrouch#196]
## Expected Behavior
No keys should be added to strings files if normalize task has set the parameter to harmonizeWithSource = false

## Actual Behavior
Keys are added with empty string as value

## Steps to Reproduce the Problem

  1. Enable normalize task
  2. Set harmonizeWithSource = false
  3. Add new terms to source language (e.g. "en")
  4. Run bartycrouch update
  5. New terms are added to target languages strings files, with value = ""

## Specifications

    Version: 4.2.0
    Platform: MacOS 10.15.6 (19G73)
    IDE Version: 11.6 (11E708)

**Comment by Jeehut** [comment]
Just merged #197 and made a new release (`4.3.1`), once https://github.com/Homebrew/homebrew-core/pull/62156 is merged, it should be available via Homebrew.
Thank you @lechuckcaptain for reporting this and the fix.
