### ISSUE TITLE
Error: Could not parse syntax tree of Swift file.

### ISSUE THREAD

**Issue by JJaviMS** [Flinesoft/BartyCrouch#199]
Hi,

I´m trying to use Bartycrouch in my project but when my Swift files are being parsed a got the following warnings for each of them: `Could not parse syntax tree of Swift file.`.
(./Project/AppDelegate.swift:  Could not parse syntax tree of Swift file.)

I also got the following warning: `Could not find 'SupportedLanguage' enum within 'BartyCrouch' enum within path.`, even when I have the file in my project.

My storyboards are correctly updated.

Swift version: 5.2
BartyCrouch version: 4.2.0
XCode version: 11.3.1

I have tried to execute BartyCrouch with the verbose option but it doesn´t provide more information.

Any idea what can be causing the problem?

**Comment by Kondamon** [comment]
In Xcode 12.0 (12A7209) I receive the same two warnings as @JJaviMS . Everything worked before but after upgrading to Xcode 12 BartyCrouch is not working anmyore.

**Comment by JJaviMS** [comment]
When I published the error I was on an old XCode version. I updated XCode to the latest version and it started working, but today when I updated XCode to the latest version (12.0 (12A7209)) I started to have the same error again in the same way @Kondamon  has pointed out.

**Comment by Kondamon** [comment]
BartyCrouch can not parse any file within XCode projects. I receive the warning `Could not parse syntax tree of Swift file.`for every file when I run `bartycrouch update -x`

**Comment by hasancaslan** [comment]
Same issue #201 #199.  I'm using _Xcode Version 12.0 (12A7209)_. 
Getting `Could not parse syntax tree of Swift file.` and 
`Could not find 'SupportedLanguage' enum within 'BartyCrouch' enum within path.`
