### ISSUE TITLE
Normalize: How do we prevent "Removing unnecessary keys"?

### ISSUE THREAD

**Issue by guidedways** [Flinesoft/BartyCrouch#202]
## Expected Behavior
This is my current configuration, I expect `harmonizeWithSource` to not remove any key it thinks is unnecessary.
```
[update.normalize]
paths = ["./strings", "./resources"]
sourceLocale = "en"
harmonizeWithSource = false
sortByKeys = true
```

## Actual Behavior
Removing keys from Localization.strings

**Comment by Jeehut** [comment]
Duplicate of #197.
