### ISSUE TITLE
Unable to add package using SPM in XCode12.

### ISSUE THREAD

**Issue by robinatrune** [Flinesoft/BartyCrouch#205]
## Expected Behavior
Able to add package.

## Actual Behavior
Fails at "Resolving package dependencies"

> because no versions of BartyCrouch match the requirement 4.2.1..<5.0.0 and package bartycrouch is required using a version-based requirement and it depends on unversion package swift-toml, BartyCrouch >=4.2.0 is forbidden.
> And because root depends on BartyCrouch 4.2.0..<5.0.0, version solving failed.

## Steps to Reproduce the Problem

  1. New -> Swift Packages -> Add Package Dependency
  2. Choose Project
  3. Add "https://github.com/Flinesoft/BartyCrouch.git" then default Rule (Version)

## Specifications

  - Version: 
  - Platform: macOS 11.0 (Big Sur)
  - IDE Version: XCode 12

**Comment by Jeehut** [comment]
@robinatrune Why are you trying to add this as a package? Are you trying to use the `BartyCrouchKit` product? Please note that BartyCrouch is not intended to be used via SwiftPM, at least I'm not aware of a feature that command line tools (what this is) are supposed to be installed via SwiftPM. I'm closing this as I think this is a misunderstanding, but I'll reopen if you explain your use case.
