### ISSUE TITLE
Install older versions of BartyCrouch

### ISSUE THREAD

**Issue by AndreMuisKP** [Flinesoft/BartyCrouch#212]
## Problem Statement

I work in a corporate environment and we can't always be on the latest version of Xcode. Currently we are on Xcode 11.5 and I've had a difficult time trying to install bartycrouch 4.2.0 (for Swift 5.2). 

## Suggested Solution

Why can't installing older versions of bartycrouch be as simple as 'brew install bartycrouch@4.2.0'? I ran 'brew search bartycrouch@' and it looks like only the current version shows up.

## Example Usage

brew install bartycrouch@4.2.0

## Possible Involvement

 - I could help with implementation: 
 - I could help with testing:

**Comment by AndreMuisKP** [comment]
Solved my own problem: brew install https://homebrew.bintray.com/bottles/bartycrouch-4.2.0.catalina.bottle.tar.gz

**Comment by Jeehut** [comment]
@AndreMuisKP Thank you. Closing this then, as you found and posted the solution.

**Comment by hien352911** [comment]
How to can i install with version 4.6.0?
