### ISSUE TITLE
The bartycrouch update command doesn't skip directories

### ISSUE THREAD

**Issue by billp** [Flinesoft/BartyCrouch#213]
## Expected Behavior
The bartycrouch update should skip the directories: ".git", "carthage", "pods", "build", ".build", "docs"

## Actual Behavior
The bartycrouch update command doesn't skip the directories: ".git", "carthage", "pods", "build", ".build", "docs"

## Steps to Reproduce the Problem
run bartycrouch update

**Comment by billp** [comment]
You can review my pull request here: https://github.com/Flinesoft/BartyCrouch/pull/214

**Comment by Jeehut** [comment]
@billp Thank you for reporting and fixing this, just released in version 4.3.2. 🎉

**Comment by billp** [comment]
Thanks @Jeehut, cheers 🍺
