### ISSUE TITLE
Machine translator failure after adding new language to project

### ISSUE THREAD

**Issue by jamiegough** [Flinesoft/BartyCrouch#215]
I'm running BartyCrouch with Microsoft Machine Translator. This worked fine up until I added a localisation language to the XCode project that isn't supported by Microsoft Machine Translator (Zulu - zu.lproj).

## Expected Behavior
Continue translating files and skip the language (Zulu) that isn't supported by the translator

## Actual Behavior
Fails when it reaches a file that is in the unsupported language with `BartyCrouch:  The operation couldn’t be completed. (MungoHealer.MungoFatalError error 1.)`

Is there a way to skip over unsupported languages throughout the project (zu.lproj) and continue translating for all other localisable files? The translations for Zulu will be added to the project manually. 

## .toml Setup: 

> [update]
> tasks = ["interfaces", "code", "transform", "normalize", "translate"]
> 
> [update.translate]
> paths = ["Components", "Storyboards", "Localisation"]
> secret = "XXX"
> sourceLocale = "en"
> 
> [update.interfaces]
> paths = ["Components", "Storyboards", "Localisation"]
> defaultToBase = false
> ignoreEmptyStrings = false
> unstripped = false
> 
> [update.code]
> codePaths = ["Components", "Storyboards", "Localisation"]
> localizablePaths = ["Components", "Storyboards", "Localisation"]
> defaultToKeys = false
> additive = true
> unstripped = false
> plistArguments = true
> 
> [update.transform]
> codePaths = ["Components", "Storyboards", "Localisation"]
> localizablePaths = ["Components", "Storyboards", "Localisation"]
> transformer = "foundation"
> supportedLanguageEnumPath = "."
> typeName = "BartyCrouch"
> translateMethodName = "translate"
> 
> [update.normalize]
> paths = ["Components", "Storyboards", "Localisation"]
> sourceLocale = "en"
> harmonizeWithSource = true
> sortByKeys = true
> 
> [lint]
> paths = ["Components", "Storyboards", "Localisation"]
> duplicateKeys = true
> emptyValues = true

## Build Output

> ...
Task 'Code Transform' took 0.584 seconds.
Starting Task 'Normalize' ...
Task 'Normalize' took 0.54 seconds.
Starting Task 'Translate' ...
info: BartyCrouch:  Translated file '/Users/Jamie/Documents/Projects/Tribe/Development/iOS/Components/TableView/af.lproj/ScheduleTableViewCell.strings' with 0 changes.
info: BartyCrouch:  Translated file '/Users/Jamie/Documents/Projects/Tribe/Development/iOS/Components/TableView/fr.lproj/ScheduleTableViewCell.strings' with 0 changes.
error: BartyCrouch:  The operation couldn’t be completed. (MungoHealer.MungoFatalError error 1.)
Starting Task 'Lint' ...
...

**Comment by Jeehut** [comment]
Fixed by https://github.com/Flinesoft/BartyCrouch/pull/219. Preparing a release now ...
