### ISSUE TITLE
XCode 12.5 not supported

### ISSUE THREAD

**Issue by mzsanford** [Flinesoft/BartyCrouch#222]
## Expected Behavior

XCode auto-updated to 12.5 and BartyCrouch is still expected to run. 

## Actual Behavior

BartyCrouch fails with the message `Could not parse syntax tree of Swift file.`. I believe this is because a new version of [SwiftSyntax](https://github.com/apple/swift-syntax) is needed but there is not yet a new release. I attempted to use the current SwiftSyntax `main` but it resulted in syntax errors during BartyCrouch compilation. 

## Steps to Reproduce the Problem

  1. Upgrade XCode to 12.5
  2. Run BartyCrouch and observe error

## Specifications

  - Version: 4.5.0
  - Platform: 11.2.3
  - IDE Version: 12.5

**Comment by Jeehut** [comment]
@mzsanford I just made a new release (4.6.0) where your update is included. It should be available via Homebrew as soon as https://github.com/Homebrew/homebrew-core/pull/76866 is merged. Thanks again for bringing this up!
