### ISSUE TITLE
Some words translated lowercased on Spanish

### ISSUE THREAD

**Issue by emreond** [Flinesoft/BartyCrouch#225]
Hello,

When I try to translate english to spanish, some words translated with lowercased.

**P.S** I found that translating this keyword on Bing also gives lowercased result.
## Example Input
"More"

## Expected Behavior
"Más"

## Actual Behavior
"más"

## Steps to Reproduce the Problem

  1. Create a key with value "More"
  2. Translate it via terminal with "bartycrouch update"
  3. See the otput

## Specifications

  - Version: 4.6.0

.bartycrouch.toml file;

`[update]
tasks = ["translate", "normalize"]

[update.interfaces]
paths = ["."]
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false

[update.code]
codePaths = ["."]
localizablePaths = ["."]
defaultToKeys = false
additive = true
unstripped = false
plistArguments = true

[update.transform]
codePaths = ["."]
localizablePaths = ["."]
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"

[update.translate]
paths = "."
secret = ""
sourceLocale = "en"

[update.normalize]
paths = ["."]
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = false

[lint]
paths = ["."]
duplicateKeys = true
emptyValues = true
`

**Comment by Jeehut** [comment]
@emreond As you already noticed in your update, this is not a defect in BartyCrouch but just the translation offered by the translation tool. As there's nothing we can do on it here within BartyCrouch, I will close this. If you have any idea what we could do to prevent this, feel free to add a comment and I'll reopen.
