### ISSUE TITLE
Error! Could not extract strings from Storyboard or XIB at path

### ISSUE THREAD

**Issue by alpennec** [Flinesoft/BartyCrouch#31]
Hello,

I don't understand why I have this error message. I have a storyboard with 2 strings files in the project.

`Error! Could not extract strings from Storyboard or XIB at path '/Users/Axel/Developer/Skipper/Skipper/Base.lproj/Activities.storyboard`

<img width="1103" alt="screenshot 2016-08-02 10 41 37" src="https://cloud.githubusercontent.com/assets/2082662/17322436/c142639c-589d-11e6-8d5f-73f267548e72.png">

<img width="709" alt="screenshot 2016-08-02 10 44 32" src="https://cloud.githubusercontent.com/assets/2082662/17322548/3ae37c18-589e-11e6-9b80-ceaecb329dc7.png">

Can you help please?
Thanks
Axel

**Comment by Dschee** [comment]
Hi @alpennec, I'd like to help you, would you mind uploading the `.storyboard` file to I can examine the issue? Also I noticed there are two `Activities.strings` files which is weird, maybe that has something to do with it?

**Comment by alpennec** [comment]
Hi @Dschee, thanks for your answer.

I have two strings because I have the base storyboard, and then a en.lproj + fr.lproj. One string file per language. Here is the file: [Activities.storyboard.zip](https://github.com/Flinesoft/BartyCrouch/files/396200/Activities.storyboard.zip)
But I have the error for all my storyboards actually: if I remove the file, the other files report the same issue.

**Sidenote**: I am using Xcode 8 b4. Maybe that's the reason? The storyboard format changed a little bit maybe. Do you have any info?

**Comment by Dschee** [comment]
Oh that may be the issue of course, haven't tested with Xcode 8 so far. Please note that BartyCrouch is actually using a command line tools provided by Xcode for extracting Strings from Storyboards and Code files, namely `ibtool` and `genstrings`. So the extraction is actually made by tools developed by Apple themselves. If there's an updated format than you may need to make sure your command line tools are updated to Xcode 8's, too. Can you check that? I'll have a look at the Storyboard meanwhile.

**Comment by Dschee** [comment]
Yeah, I can reproduce the issue with your file. Gonna have a look sometime later today, can't find an obvious reason for it. But may have to do with Xcode 8.

**Comment by alpennec** [comment]
@Dschee my bad, I forgot to switch the Xcode version after installing BartyCrouch (I needed to use the Xcode 7 version to install BartyCrouch, but forgot to rollback to the beta version). It is now working correctly 👍

![screenshot 2016-08-02 11 23 23](https://cloud.githubusercontent.com/assets/2082662/17323790/b7c8f424-58a3-11e6-81b1-c1571b0c8cf3.png)

Thanks for you help.

**Comment by Dschee** [comment]
You're welcome, glad I could help. Also nice to hear BartyCrouch works with Xcode 8 (at least basically) without any changes. 👍
