### ISSUE TITLE
Fails completely if a single translation file is missing

### ISSUE THREAD

**Issue by Dschee** [Flinesoft/BartyCrouch#36]
BartyCrouch isn't doing anything if any of the Storyboard files is missing a translation. For example if English, Polish and Russian are specified as the projects supported languages, and there are `Main.storyboard` and `LaunchScreen.storyboard`, both base-internationalized but only for Russian and Polish, not for English, then BartyCrouch currently fails completely with "Error! No input files found." which is too general.

We could do one of the following:
1. make BartyCrouch more resilient against missing files (so that the existing ones work)
2. improve the error by stating that all specified project languages must be met by all IB files
3. combine both by introducing a check for each IB file, listing the missing ones as a warning but processing the existing

**Comment by HackDeveloperUA** [comment]
Hi !
Be sure to turn the English localization into the Main.Storyboard and LaunchScreen.storyboard
![zrzut ekranu 2016-10-24 o 23 45 58](https://cloud.githubusercontent.com/assets/13185966/19665391/1221189c-9a45-11e6-8a7c-7ee4828f85f2.png)
![zrzut ekranu 2016-10-24 o 23 48 41](https://cloud.githubusercontent.com/assets/13185966/19665390/121966a6-9a45-11e6-978c-21486fa34017.png)

**Comment by Dschee** [comment]
Hello guys, I just released version 3.7.2 which fixes a similar issue. I didn't do any of the above changes though, but it might still have fixed this issue in it's basics (preventing BartyCrouch from crashing). As we don't have a test to reproduce this issue, I can't simply test it and have to rely on you guys instead.

Also, if anybody comes across this issue with BartyCrouch version 3.7.2 or newer again, please report this here as well (because it would mean this isn't fixed).

Thanks for your support!

**Comment by Dschee** [comment]
I consider this fixed until somebody reports that it's not. See above comment.
