### ISSUE TITLE
Terminating app due to uncaught exception 'NSInternalInconsistencyException'

### ISSUE THREAD

**Issue by terenzeyuen** [Flinesoft/BartyCrouch#37]
Help, latest xcode keep getting this no matter what I do. Runs fine if i disable the script?

BartyCrouch: Successfully updated strings file(s) of Storyboard or XIB file.
2016-10-30 21:21:49.855 bartycrouch[32900:1074407] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Couldn't posix_spawn: error 7'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff7d0e952b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff917c1cad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff7d167a0d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff7eafcc7e -[NSConcreteTask launchWithDictionary:] + 3134
	4   bartycrouch                         0x000000010f5c504b bartycrouch + 192587
	5   bartycrouch                         0x000000010f5ccb57 bartycrouch + 224087
	6   bartycrouch                         0x000000010f5c6e77 bartycrouch + 200311
	7   bartycrouch                         0x000000010f5c7a8d bartycrouch + 203405
	8   bartycrouch                         0x000000010f5ca365 bartycrouch + 213861
	9   bartycrouch                         0x000000010f5ae54c bartycrouch + 99660
	10  bartycrouch                         0x000000010f597ef9 bartycrouch + 7929
	11  libdyld.dylib                       0x00007fff9209f255 start + 1
	12  ???                                 0x0000000000000007 0x0 + 7
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by terenzeyuen** [comment]
Noticed this happens after cocoapods install?

**Comment by terenzeyuen** [comment]
Solved it by using project name after dir..
if which bartycrouch > /dev/null; then
# Incrementally update all Storyboards/XIBs strings files
bartycrouch interfaces -p "$PROJECT_DIR/$PROJECT_NAME"

# Add new keys to Localizable.strings files from NSLocalizedString in code
bartycrouch code -p "$PROJECT_DIR/$PROJECT_NAME" -l "$PROJECT_DIR/$PROJECT_NAME" -a
else
echo "warning: BartyCrouch not installed, download it from https://github.com/Flinesoft/BartyCrouch"
fi

**Comment by Dschee** [comment]
Hi @terenzeyuen, thanks for asking and then solving your own problem. That's a strange error and if that happens for others, too, It'd be great to get more detailed information so we can fix it. I'm not sure what you mean with 'cocoapods install', BartyCrouch is not a pod, it's installed via Homebrew. Nevertheless, happy you could solve your problem! 👍
