### ISSUE TITLE
Comments are not being updated with `code` option

### ISSUE THREAD

**Issue by marc-inn** [Flinesoft/BartyCrouch#38]
Given that I have fully translated app with `code` String files
And I have String `let sample = NSLocalizedString("category.sample", comment: "Sample")`
When I change a comment for `sample` String to `comment: "New Sample"`
Then comment is not updated in Strings file.

Are you going to implement that feature in future?

Btw. super useful tool! Thanks

**Comment by Dschee** [comment]
Hi @marc-inn, thank you for your feature request. I just made an attempt to implement this and released a new version with it (3.4.0). Please upgrade BartyCrouch (e.g. via `brew update && brew upgrade flinesoft/bartycrouch/bartycrouch`) and use the new option `override-comments` (short `-c`) on the `code` sub command – also documented in the README [here](https://github.com/Flinesoft/BartyCrouch#override-comments-aka--c---override-comments-optional).

I hope this works, I haven't had the time to test it myself, but it might work. Please reopen the issue if it doesn't, I'm closing for now.

**Comment by marc-inn** [comment]
Working great! 

I posted PR with small update, that made comments working for me. 

Thanks

**Comment by Dschee** [comment]
Ahh yeah, I forgot that one. Great catch!

Would you mind also adding a test within your PR for the `overrideComments` option? That would be great to make sure the feature doesn't break in future releases. If not, I'll try to add one sometime later when I have more spare time. :)

**Comment by marc-inn** [comment]
No problem :P Tests added.

**Comment by Dschee** [comment]
That was not exactly what I was looking for, but never mind, I'm merging it anyway, we can add tests for the `overrideComments` options change logic regarding the Strings files later on. ;)

**Comment by Dschee** [comment]
I just released v3.4.1 with your bug fix. Thanks again!

**Comment by banoslo** [comment]
This is an issue again since we have to use 'bartycrouch update' instead of 'bartycrouch code'. Or am I missing something?

**Comment by Dschee** [comment]
Yes, you are missing something. There is no „code“ subcommand anymore starting with version 4 of BartyCrouch. Please refer to the [migration guide](https://github.com/Flinesoft/BartyCrouch/blob/stable/MIGRATION_GUIDES.md#upgrade-from-3x-to-4x) and the config section in the README for more information.

**Comment by lahariganti** [comment]
https://github.com/Flinesoft/BartyCrouch/blob/main/Sources/BartyCrouchKit/TaskHandlers/CodeTaskHandler.swift seems to use a preset value of `false` for `overrideComments`  . . . ? the below is how my `.bartycrouch.toml` looks like; seems like I am missing something key in the README
```
[update]
tasks = ["interfaces", "code", "normalize"]

[update.interfaces]
paths = ["."]
defaultToBase = true 
ignoreEmptyStrings = false 
unstripped = true 

[update.code]
codePaths = ["."] 
localizablePaths = ["."]
defaultToKeys = true 
additive = false 
overrideComments = true
unstripped = true

[update.normalize]
paths = ["."]
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
paths = ["."]
duplicateKeys = true
emptyValues = true
```

**Comment by noah-nuebling** [comment]
Hi! Is the `overrideComments` option still available? It doesn't seem to work for me. 

I can only get the comments to change if I completely delete a key from the .strings file before running `bartycrouch update`

I'm on macOS 13.0 Beta (22A5321d), using bartycrouch 4.11.0, and my `.bartycrouch.toml` looks like this:

```
[update]
tasks = ["interfaces", "code", "normalize"]

[update.interfaces]
paths = ["app", "helper", "accomplice"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "frameworks", "tests", "*/external", "*/SupportFiles", "*/iOS-Polynomial-Regression-master"]
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false
ignoreKeys = ["#bartycrouch-ignore!", "#bc-ignore!", "#i!"]

[update.code]
overrideComments = true
codePaths = ["app", "helper", "accomplice"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "frameworks", "tests", "*/external", "*/SupportFiles", "*/iOS-Polynomial-Regression-master"]
localizablePaths = ["./Localization"]
defaultToKeys = false
additive = false
unstripped = false
plistArguments = true
ignoreKeys = ["#bartycrouch-ignore!", "#bc-ignore!", "#i!"]

[update.transform]
codePaths = ["app", "helper", "accomplice"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "frameworks", "tests", "*/external", "*/SupportFiles", "*/iOS-Polynomial-Regression-master"]
localizablePaths = ["./Localization"]
transformer = "foundation"
supportedLanguageEnumPath = "."
typeName = "BartyCrouch"
translateMethodName = "translate"
separateWithEmptyLine = true

[update.normalize]
paths = ["app", "helper", "accomplice"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "frameworks", "tests", "*/external", "*/SupportFiles", "*/iOS-Polynomial-Regression-master"]
sourceLocale = "de"
harmonizeWithSource = true
sortByKeys = true
separateWithEmptyLine = true

[lint]
paths = ["app", "helper", "accomplice"]
subpathsToIgnore = [".git", "carthage", "pods", "build", ".build", "docs", "frameworks", "tests", "*/external", "*/SupportFiles", "*/iOS-Polynomial-Regression-master"]
duplicateKeys = true
emptyValues = true
```

Let me know if I should create an issue for this.

**Comment by Jeehut** [comment]
@noah-nuebling If an option is documented in the README, it is still supported. Feel free to report an issue.

**Comment by noah-nuebling** [comment]
Alright @Jeehut, I posted an issue. It's mostly copy pasted from the comment but I added some extra details.

**Comment by Jeehut** [comment]
FYI: @noah-nuebling's issue was fixed in the meantime and this should fully work again in version 4.13.0+.
