### ISSUE TITLE
Swift NSLocalizedString with more than 2 arguments silently ignored

### ISSUE THREAD

**Issue by fvolchyok** [Flinesoft/BartyCrouch#41]
According to https://openradar.appspot.com/22133811 and my personal experience, genstrings doesn't add strings with more than 2 arguments (key and comment) and ignores such strings with (unfortunately not helpful) error message. 
The solution would be to switch to extractLocString (http://stackoverflow.com/a/38143845/2305175).

**Comment by Dschee** [comment]
Well that's interesting, seems like `genstrings` was only created for the initial two-arguments NSLocalizedString. Switching to extractLocStrings seems to be the right choice and I think we should actually do that. I'll have a look into it once I have some spare time and after fixing some of the other issues. If you need it now, feel free to fork and implement the change yourself.

I would suggest that we first introduce an option to test the new script in practice before making it the default. So let's introduce a `ExtractLocStringsCommander` class alongside the existing `GenStringsCommander` and use it if an option like `-e` or (long) `--extract-loc-strings` is specified. That would be done in a minor version release. If all seems to be fine with `extractLocStrings` then we can make it the new default in a major release.

**Comment by fvolchyok** [comment]
I've created a pull request https://github.com/Flinesoft/BartyCrouch/pull/43. Unfortunately, I created and closed unnecessary one in process. My apologies.

**Comment by Dschee** [comment]
I consider this closed as #43 is merged. I plan to release a minor version update within the next few hours with the new option – thanks for contributing! 🎉

**Comment by Dschee** [comment]
Version 3.5.0 was just released and includes this feature. I hope it works for you as expected!
