### ISSUE TITLE
Missing Support of Generating Multiple Comments of Same Key?

### ISSUE THREAD

**Issue by vinceplusplus** [Flinesoft/BartyCrouch#44]
Suppose I have the following code:
```swift
let s1 = NSLocalizedString("test", comment: "test comment 1")
let s2 = NSLocalizedString("test", comment: "test comment 2")
```

BC generated .strings file becomes:
```
"test" = "test";
```

However, with the original genstrings, the generated file would become:
```
/* test comment 1
   test comment 2 */
"test" = "test";
```

**Comment by Dschee** [comment]
@vinceplusplus Thank you for reporting your issue. Up until now BartyCrouch only had support for single-line comments. This is now changed and I'm gonna release version 3.6.0 within the next hour with support for the requested multi-line comment feature.

I hope it'll work for you now! :)
