### ISSUE TITLE
Build script fails with only interfaces subcommand

### ISSUE THREAD

**Issue by Zamuzo** [Flinesoft/BartyCrouch#50]
Hi,

I don't want incrementally updates localizable.string but this code return "Command /bin/sh failed with exit code 78"
 
`if which bartycrouch > /dev/null; then
    bartycrouch interfaces -p "$PROJECT_DIR" -b
else
    echo "warning: BartyCrouch not installed, download it from https://github.com/Flinesoft/BartyCrouch"
fi`

What's wrong ?

Thanks in advance :D

**Comment by Dschee** [comment]
I can't really tell without an example project to test this against. But be sure to check if you have the same issue as explained in https://github.com/Flinesoft/BartyCrouch/issues/36. Also your title isn't describing your problem, I'm renaming it to something more suitable.

**Comment by Dschee** [comment]
Closing this, as no answer provided for long time to clarify the issue.
