### ISSUE TITLE
"Command /bin/sh failed with exit code 139" if no localizables

### ISSUE THREAD

**Issue by Dschee** [Flinesoft/BartyCrouch#52]
Fails with an error "Command /bin/sh failed with exit code 139" when the Localizable.strings file is empty.

**Comment by mathieuedet** [comment]
I've exactly the same error for the code translating. Even if Localizable.strings files are not empty, it doesn't work... Have you a solution for this problem ?

**Comment by Dschee** [comment]
Hi @mathieuedet, thank you for reporting this. What version of BartyCrouch are you using? You can check with `brew info bartycrouch`. Then, did you also make sure you're not walking into this problem: https://github.com/Flinesoft/BartyCrouch/issues/36? Next, can you also check if you have any other empty Strings files like localized Storyboards?

If all that doesn't help, could you provide an example project (you can also send it to me privately, see my profile for email address) so I can analyze when I have some spare time.

**Comment by Dschee** [comment]
I've just fixed a possible source for BartyCrouch to crash (due to unexpected behaviour of the Apple tools used within it) and released version 3.7.2 with it. @mathieuedet If you still have the issue, feel free to check if it is fixed for you.

**Comment by Dschee** [comment]
As there was no answer on this for a while and an attempt was made to fix it, I consider this closed until somebody proves it otherwise.
