### ISSUE TITLE
Looking for a video tutorial. 

### ISSUE THREAD

**Issue by rlam3** [Flinesoft/BartyCrouch#56]
Looking for a video tutorial. Anybody wanna take a shot at this? I'm confused on how to set bartycrouch up with Xcode 8.3 with the default preexisting localized procedures.

Installing bartycrouch isn't the problem. Its integrating bartycrouch with current existing Xcode project with a prior Localized strings. 

Also I've also been arriving at a Sementation fault: 11 but it doesn't show where the fault is coming from when I run the following command.

```bash
bartycrouch code -p "localization1" -l "localization1/" -a
```

Also, does BartyCrouch allow or enable user to switch between languages of the user choosing without through device settings? 

Thanks!

**Comment by Dschee** [comment]
A video tutorial definitely is a good idea. I'm gonna be on vacation in about two weeks, I think I might be tackling it alongside #36. If you want to provide me with an example project (you can send it to my email address if you don't want it to be public – I'll not upload the code anywhere, promise!) then I can also elaborate what the problem in your specific case is.

On the "switch languages without going through device settings front" I've actually searched for that recently, too and implemented such a feature in my Prayer app that I released just yesterday here: https://github.com/Flinesoft/Prayer

Look for the code in [this class](https://github.com/Flinesoft/Prayer/blob/stable/Sources/Code/SettingsViewController.swift) and the methods `setupAppSection()` and `showRestartConfirmDialog()` in specific. I've also explained the relevant parts in detail in [this SO answer](http://stackoverflow.com/a/41773503/3451975) so you might want to check that out.

By the way, the Prayer app also includes a build script that runs BartyCrouch on every build, so maybe until the video is done that example might help you out.

I hope this helps.

**Comment by Dschee** [comment]
I'm closing this as this is neither a bug nor a feature request – it was merely a question which I answered. If the answer proves insufficient, then I'm happy to open it again. But until then I consider this solved.
