### ISSUE TITLE
Homebrew issue

### ISSUE THREAD

**Issue by esetnik** [Flinesoft/BartyCrouch#57]
Today when updating homebrew repositories I receive the following:

```
> brew up
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error: Fetching /usr/local/Homebrew/Library/Taps/flinesoft/homebrew-bartycrouch failed!
```

**Comment by Dschee** [comment]
Yes, this is actually a new feature and I'm sorry for the inconvenience. But in the long term the fact that **BartyCrouch now is part of HomeBrew-Core** is going to be a good thing.

Please follow the instructions I've added to the README. Specifically:

> If you had installed a previous version (<= 3.8.0) via the tap, you should run the following once:
>
> `$ brew untap flinesoft/bartycrouch`

From then on, it should all work again – if not, you should **update homebrew** via `brew update`.
To install a new version of BartyCrouch in the future, you can now simply call `brew upgrade bartycrouch`.

If nothing else works, you can try uninstalling BartyCrouch and reinstall it via HomeBrew-Core like this:
```shell
brew uninstall bartycrouch
brew install bartycrouch
```

Please tell me, if this helps and which steps were needed, so others can profit from it, too.
Thanks for you understanding!

**Comment by esetnik** [comment]
`brew untap flinesoft/bartycrouch` was all I needed. Thanks for the update.
