### ISSUE TITLE
Add default to comment option to code sub-command

### ISSUE THREAD

**Issue by mkj-is** [Flinesoft/BartyCrouch#58]
First, thank you for creating this great tool!

In our workflow we usually add the default localization in comments, there is a possibility to add keys as a default value to the localized files. I think option `-c` or `--default-to-comment` to add comments as default values for code sub-command would be a great complement to the `--default-to-keys` option.

What do you think about it?

**Comment by Dschee** [comment]
Is what you describe a feature supported by Apple or something widely used in the community and defined somewhere? I want BartyCrouch to cover any possible best practice, so I'd not say "no" to a good pull request from you that also includes tests for your case. If there wider use of your feature, I'd like to link the resource in the README. If there's not, I'd like to at least have an explanation of what the advantage is against the common usage pattern described by Apple [here](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/LoadingResources/Strings/Strings.html).

**Comment by Dschee** [comment]
I'd like to come back to this feature request. Unfortunately nobody has answered my questions but I can see that some people seem to have given a thumbs up to this feature. Again: I'm open to merge a PR that adds this feature. And I'm still curious how you want to tell your translators the context of a translation string if you can't use the comment any more?

If no one answers here again, I have to close this feature request. A PR would make me happier though! ;)
