### ISSUE TITLE
Support install via CocoaPods

### ISSUE THREAD

**Issue by Econa77** [Flinesoft/BartyCrouch#60]
Thank you for creating a great tool 👍 

Is it possible to install via CocoaPods like [SwiftLint]( https://github.com/realm/SwiftLint/issues/939)?
By version control via CocoaPods, it makes it easier for multiple people to develop, oss development and more.

**Comment by Dschee** [comment]
I think nothing speaks against providing an additional way of installing BartyCrouch. I won't have time to do this soon though, as I'm currently concentrating on [this project](https://github.com/Flinesoft/Raid-Meetup-for-Pokemon-GO) and the PRs https://github.com/Moya/Moya/pull/1147 and https://github.com/Carthage/Carthage/pull/1990 in my free time.

I'd gladly have allok on a good PR though, would you want to do this yourself?

**Comment by Econa77** [comment]
Ok 👍 
I would like to create a Makefile that can create a frameworks summarized by zip like Swiftlint.
And will submit PR.

**Comment by Dschee** [comment]
Feel free to do whatever is needed to get this feature going. As long as it doesn't affect the already existing features and providing this via Homebrew, I'm completely fine with it.

**Comment by Dschee** [comment]
I've merged #61 and made a new release (3.8.1) with your instructions. Please report if it doesn't work for you. Thanks you for this feature! 🎉

**Comment by Econa77** [comment]
@Dschee Thank you for releasing new version. 👍 I tried it with the own application, it works perfectly.
https://github.com/Clipy/Clipy/blob/81362693e08cec219448f191a33f96d0473866fa/Podfile#L22

I can not check the library on cocoapods.org, but are you planning to push this version?

Thanks 😄

**Comment by Dschee** [comment]
Oh yearh, sure, forgot the last step after getting excited too early. 😄 

Just uploaded it, should be available now! 🎉
