### ISSUE TITLE
Option to Exclude path to avoid picking up localisation from Pods and imported libs

### ISSUE THREAD

**Issue by romanr** [Flinesoft/BartyCrouch#63]
Would be great to have --exclude path option, to avoid picking up localisation from Pods and  imported libraries

For example project has this structure:

 - Module1
 - Module2
 - Module3
 - Pods

running `bartycrouch code -p . ` will include localization from Pods or any third party libraries happen to be relative to project root. It mixes those 3rd party strings into your Localizable.strings.

Yes, the sources can be organized under something like /src in root of project, but that never happens. Sources are never in their own separate subtree.

As workaround paths can be included by running command multiple times. `bartycrouch code -p Module1 ` , `bartycrouch code -p Module2` etc. but that is not sustainable.

**Comment by Dschee** [comment]
What about we simply add `Pods/` to [this array](https://github.com/Flinesoft/BartyCrouch/blob/0b725648f67dca45fafc93be31c5557e963058da/Sources/Code/StringsFilesSearch.swift#L62)? That should solve your problem easily, wouldn't it?

**Comment by romanr** [comment]
Yes, of course `Pods/` should be added there.

Still, there may be cases when you integrate some library by copying sources or using git submodule and it appears in project root among your regular sources.

**Comment by Dschee** [comment]
Sure, there could be such cases. If you want, you can add options named `exclude` and `include` for such cases which are whitelists or blacklists of folders. But I think using a folder named `Source` (or `ProjectName` which is Xcodes default) is an existing workaround which is also a good idea in general (e.g. the Swift Package Manager recommends this as well).

Unfortunately I don't have much free time right now to fix issues that are no real problems. You had a real problem with the Pods folder which many others might have, too. So I suggested a solution for that. For any other ideas I'm thankful for your issue but I won't have time to deal with it anytime soon. I'd merge it though if it was implemented, tested and documented. :)

**Comment by romanr** [comment]
No problem. Should I add `Pods/` there or you will do it?

**Comment by Dschee** [comment]
A PR would be nice! 🙂

**Comment by mygzi** [comment]
The fix from dd5d07e doesn't address the OP's request to avoid pulling in 3rd party (cocoapod) strings. The array to which `Pods/` was added filters the `-l /directory/containing/all/Localizables` path rather than the `-p /path/to/code/directory` path.

I've implemented a similar directory filter in `CodeCommander.findFiles` which does the trick in our project. Would you prefer to reopen this issue or start a new one?

**Comment by Dschee** [comment]
Please open a new issue and feel free to post your change as a PR, independent from which issue it fixes. Would be great 👍

**Comment by sh95014** [comment]
The discussion appears to continue at https://github.com/Flinesoft/BartyCrouch/issues/156
