### ISSUE TITLE
findFiles() hanging indefinitely

### ISSUE THREAD

**Issue by donnellyk** [Flinesoft/BartyCrouch#72]
In 3.9, w/ changing of the order of reading the standard output/error, `/usr/bin/find` is now hanging indefinitely for me. 

If I swap the order so `standardOutput` is read first, it works as expected with ~1000 files found and 0 errors: 
```
(lldb) po errdata.isEmpty
true
```

## Reproducing
The magic number (on my machine, at least. `macOS 10.12.6, Xcode 9.0 9A235`) seems to be 983 files, anything over that and it seems to hang. I've attached a zip file with a file hierarchy that reproduced the bug on my machine. It is just a bunch of empty `.swift/h/m` files in folders.

[files.zip](https://github.com/Flinesoft/BartyCrouch/files/1353317/files.zip)

**Comment by donnellyk** [comment]
It seems like no where in the code base are the errors actually used. If others can reproduce and you agree, I could put up a PR that just removes the reading of `stdError`.

**Comment by Dschee** [comment]
Hi @donnellyk and thank you for the bug report. Feel free to open a PR with your suggested fix.

**Comment by stachon** [comment]
Don't know if this is related, but since High Sierra, `bartycrouch code` always hangs for me. A workaround is to exclude `/Pods` directory, ie. `bartycrouch code -p "$PROJECT_DIR/TargetName"`

**Comment by Dev-** [comment]
Can confirm excluding Pods directory stopped the hanging for me as well.

**Comment by Dschee** [comment]
@stachon & @Dev- We have [this line](https://github.com/Flinesoft/BartyCrouch/blob/stable/Sources/Code/StringsFilesSearch.swift#L74) where some directories are excluded from the file search. The list also includes `Pods/`, maybe we need to use this list somewhere else, too? Just as a hint.

Other than that, feel free to investigate the issue and post a PR with your fix. Best would be, if that fix also included a test which fails without it so we can make sure this problem doesn't arise again.
