### ISSUE TITLE
External launch of find causes race condition

### ISSUE THREAD

**Issue by ClementPadovani** [Flinesoft/BartyCrouch#77]
I thought that my fix #76 would fix #72, it doesn't in every case.

I figured out that the issue was when we were dealing with a large codebase 

Since the Process is being spawned in a pseudo-synchronous mode https://github.com/Flinesoft/BartyCrouch/blob/545534297e43061ef46f5db8cf26a6a66809f8c5/Sources/Code/Commander.swift#L29

And, calling Process.waitUntilExit https://github.com/Flinesoft/BartyCrouch/blob/545534297e43061ef46f5db8cf26a6a66809f8c5/Sources/Code/Commander.swift#L47 isn't suitable here, per Mike Ash's [article](https://www.mikeash.com/pyblog/friday-qa-2009-11-13-dangerous-cocoa-calls.html).

To remediate this issue, FileManager looks like a good candidate for the `CodeCommander.findFiles()` method.

**Comment by Dschee** [comment]
I'm guessing this was fixed with the merge of #78. Closing.

Thanks again @ClementPadovani for the issue and the fix! 🎉
