### ISSUE TITLE
Is it possible to localize all storyboards and xibs in the project?

### ISSUE THREAD

**Issue by wilkins-mydreams** [Flinesoft/BartyCrouch#81]
I am trying to find a way to generate string files for all storyboards and xibs in my project, is this possible with BartyCrouch? I found this [script](https://gist.github.com/yoichitgy/29bdd71c3556c2055cc0) but it seems that it is not working anymore

**Comment by Dschee** [comment]
Nope, this feature is out of scope of BartyCrouch's feature set. BartyCrouch isn't a toolset for "everything about translation related", it's merely here to serve one single goal: To fix Xcode which should have an incremental update feature by itself, but doesn't.

I recommend you write a new script yourself using [Beak](https://github.com/yonaskolb/Beak). It even allows you to include SPM dependencies. Feel free to share it with the community afterwards.
