### ISSUE TITLE
Localizable strings are being mirrored into all storyboard .strings files

### ISSUE THREAD

**Issue by AlexGingell** [Flinesoft/BartyCrouch#88]
I'm seeing a very strange problem after upgrading BartyCrouch to v3.10 today.  Unfortunately I don't know exactly which version I upgraded _from_, but I do know that it was v3.x.

Prior to the upgrade, BC would correctly detect NSLocalizedString() macros in my source code and place these strings in Localizable.strings as expected (and only there).  It would also pick up any strings in my storyboards and and place them in the corresponding storyboard .strings files. All good.

After the upgrade, NSLocalizedString strings are still sent to Localizable.strings, but are also being mirrored into every storyboard .strings file in my project - even storyboards that do not have any strings in them and whose .strings files should be completely empty.

My build phase script remains unchanged and is based on your example:

```
if which bartycrouch > /dev/null; then
# Incrementally update all Storyboards/XIBs strings files.
bartycrouch interfaces -p "$PROJECT_DIR/Werble" --default-to-base
# Add new keys to Localizable.strings files from NSLocalizedString in code
bartycrouch code -p "$PROJECT_DIR/Werble" -l "$PROJECT_DIR/Werble/Supporting Files" -a --default-to-keys
else
echo "warning: BartyCrouch not installed, download it from https://github.com/Flinesoft/BartyCrouch"
fi
```

Supporting Files contains all storyboards and strings files, 'Werble' is a directory in the project root containing source code and the supporting files directory.

I'm scratching my head over this one - nothing changed in the project in the interim - am I doing something silly?  Thank you for any help.

Alex

**Comment by Dschee** [comment]
I just reverted #67 and released version 3.10.1 – it should be available via Homebrew within the next 24 hours. Please have a look if your problem is now solved or still appears to be happening.

**Comment by AlexGingell** [comment]
Thank you @Dschee - I will do exactly that and report back here.

**Comment by AlexGingell** [comment]
@Dschee I can confirm that v3.10.1 appears to fix this issue. Thank you for your prompt response! ;)

**Comment by Dschee** [comment]
Glad I could help!

**Comment by mathebox** [comment]
I can have a look at this.
