### ISSUE TITLE
It's very hard to build

### ISSUE THREAD

**Issue by LitDragon** [Flinesoft/BartyCrouch#89]
It's a long time to build and run. Is that a problem?

**Comment by Dschee** [comment]
Sorry, this is really not a useful description. I need more information to help, for example:
- What are you building?
- Are you installing BartyCrouch where it's slow?
- Are you running a specific command where it's slow?
- Which command are you running? Which parameters are you using?
- What is the size and structure of your project? Can you show us a demo project?
- How long is "long time" for you? Longer than 3 seconds? Or longer than 3 minutes?
- What version of Xcode do you have installed?
- What version of BartyCrouch are you using?
- Did the issue happen in earlier versions, too?

**Comment by LitDragon** [comment]
Nothing, thank you
