### ISSUE TITLE
Cocoapods use

### ISSUE THREAD

**Issue by simonbromberg** [Flinesoft/BartyCrouch#97]
How are you meant to use Barty Crouch if you install it via Cocoapods? It doesn't install it into the terminal…?

**Comment by simonbromberg** [comment]
Maybe the readme should be updated to provide more clear instructions for
cocoapods?

**Comment by Dschee** [comment]
@simonbromberg That‘s right, I‘m reopening. Would you like to post a PR with a change that you feel will explain usage good enough?

**Comment by Dschee** [comment]
CocoaPods supports was dropped in version 4. Readding was requested in #118, I'm closing this though as long as that is open. We should probably include the detailed REAME explanation if #118 is fixed.
