### ISSUE TITLE
link is broken

### ISSUE THREAD

**Issue by thierryH91200** [Flinesoft/BartyCrouch#98]
#### ID and Secret (aka `-i` and `-s`, `--id` and `--secret`) <small>*required*</small>

BartyCrouch acts as a client for the Microsoft Translator API. In order to use that API you need to **register [here](https://datamarket.azure.com/dataset/bing/microsofttranslator)** (the free tier allows for 2 million translations/month). Then you can **add a client [here](https://datamarket.azure.com/developer/applications)** which will provide you the `id` and `secret` credentials required for machine-translation.

https://datamarket.azure.com/developer/applications
https://datamarket.azure.com/dataset/bing/microsofttranslator
the links are dead
can you help me ??

**Comment by Dschee** [comment]
See #54, integration with Microsoft Translator wasn't tested for some time now. Microsoft changed their APIs but our dependency Polyglot didn't get an update, so we probably need to add proper support ourselves. When that's tackled, the README will be updated as well. Also we should add support for other services like Google Translator, at least the Microsoft Translator implementation should be abstract enough to add other translation services easily.

**Comment by Dschee** [comment]
@thierryH91200 Please note that I'm currently preparing the beta release phase of Version 4.0 where this issue is fixed. Just in case you're still interested in machine translation via BartyCrouch.

**Comment by thierryH91200** [comment]
thanks  and 2 stars for FIFA World Championship 2018

**Comment by Dschee** [comment]
This was fixed in #114.
